version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-chatbot-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ugn4udg1fm6d"
s3_prefix = "sam-chatbot-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
